name: api_docs
description: >
  Pubspec used to fetch specific versions of packages for the purpose of generating API docs,
  and for checking if new versions are available (see gulp/pkg-vers.js).
version: 0.0.1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0
  angular_forms: ^2.1.1
  angular_router: ^2.0.0-alpha+21
  angular_test: ^2.2.0

dev_dependencies:
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
